---
title: "git_01"
author: "Mariah Kee"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
How doth the little crocodile  
     Improve his shining tail,  
And pour the waters of the Nile   
     On every golden scale!  
  
How cheerfully he seems to grin,  
     How neatly spreads his claws,  
       
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
'The wonder is I didn't see at once.  
I never noticed it from here before.  
I must be wonted to it--that's the reason.  
The little graveyard where my people are!  
So small the window frames the whole of it.  
   
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
“You are old, Father William,” the young man said,  
“And your hair has become very white;  
And yet you incessantly stand on your head –  
Do you think, at your age, it is right?”  

“In my youth,” Father William replied to his son,  
“I feared it might injure the brain;  